{
  "rows": 7,
  "cols": 7,
  "walls": [
    [
      0,
      5
    ],
    [
      1,
      0
    ],
    [
      2,
      2
    ],
    [
      2,
      3
    ],
    [
      3,
      4
    ],
    [
      4,
      0
    ],
    [
      4,
      6
    ],
    [
      5,
      0
    ],
    [
      5,
      3
    ],
    [
      6,
      4
    ]
  ],
  "terminal_states": [],
  "rewards": [
    {
      "state": [
        0,
        6
      ],
      "value": 1.0
    },
    {
      "state": [
        1,
        4
      ],
      "value": 1.0
    },
    {
      "state": [
        3,
        3
      ],
      "value": -1.0
    },
    {
      "state": [
        3,
        5
      ],
      "value": -1.0
    }
  ],
  "p_forward": 0.8,
  "gamma": 0.99,
  "step_reward": -0.05,
  "start_state": [
    6,
    0
  ]
}
