{
  "rows": 15,
  "cols": 15,
  "walls": [
    [
      0,
      6
    ],
    [
      0,
      8
    ],
    [
      1,
      2
    ],
    [
      2,
      5
    ],
    [
      2,
      9
    ],
    [
      3,
      14
    ],
    [
      5,
      4
    ],
    [
      5,
      14
    ],
    [
      6,
      13
    ],
    [
      7,
      1
    ],
    [
      8,
      2
    ],
    [
      9,
      1
    ],
    [
      9,
      7
    ],
    [
      9,
      9
    ],
    [
      9,
      11
    ],
    [
      10,
      10
    ],
    [
      11,
      6
    ],
    [
      13,
      0
    ],
    [
      13,
      1
    ],
    [
      13,
      2
    ],
    [
      13,
      5
    ],
    [
      13,
      11
    ]
  ],
  "terminal_states": [],
  "rewards": [
    {
      "state": [
        0,
        14
      ],
      "value": 1.0
    },
    {
      "state": [
        9,
        4
      ],
      "value": 1.0
    },
    {
      "state": [
        1,
        4
      ],
      "value": 1.0
    },
    {
      "state": [
        10,
        0
      ],
      "value": 1.0
    },
    {
      "state": [
        7,
        14
      ],
      "value": -1.0
    },
    {
      "state": [
        6,
        14
      ],
      "value": -1.0
    },
    {
      "state": [
        1,
        12
      ],
      "value": -1.0
    },
    {
      "state": [
        9,
        5
      ],
      "value": -1.0
    },
    {
      "state": [
        9,
        6
      ],
      "value": -1.0
    }
  ],
  "p_forward": 0.8,
  "gamma": 0.99,
  "step_reward": -0.05,
  "start_state": [
    14,
    0
  ]
}
