{
  "rows": 13,
  "cols": 13,
  "walls": [
    [
      0,
      4
    ],
    [
      0,
      6
    ],
    [
      0,
      9
    ],
    [
      1,
      2
    ],
    [
      1,
      12
    ],
    [
      2,
      2
    ],
    [
      2,
      4
    ],
    [
      2,
      12
    ],
    [
      5,
      0
    ],
    [
      5,
      3
    ],
    [
      5,
      5
    ],
    [
      6,
      3
    ],
    [
      6,
      6
    ],
    [
      6,
      8
    ],
    [
      8,
      8
    ],
    [
      8,
      10
    ],
    [
      9,
      7
    ],
    [
      10,
      1
    ],
    [
      12,
      12
    ]
  ],
  "terminal_states": [],
  "rewards": [
    {
      "state": [
        0,
        12
      ],
      "value": 1.0
    },
    {
      "state": [
        5,
        1
      ],
      "value": 1.0
    },
    {
      "state": [
        3,
        9
      ],
      "value": 1.0
    },
    {
      "state": [
        8,
        11
      ],
      "value": -1.0
    },
    {
      "state": [
        4,
        0
      ],
      "value": -1.0
    },
    {
      "state": [
        11,
        3
      ],
      "value": -1.0
    },
    {
      "state": [
        2,
        9
      ],
      "value": -1.0
    }
  ],
  "p_forward": 0.8,
  "gamma": 0.99,
  "step_reward": -0.05,
  "start_state": [
    12,
    0
  ]
}
