{
  "rows": 17,
  "cols": 17,
  "walls": [
    [
      1,
      2
    ],
    [
      2,
      7
    ],
    [
      2,
      13
    ],
    [
      3,
      2
    ],
    [
      4,
      3
    ],
    [
      5,
      15
    ],
    [
      6,
      12
    ],
    [
      7,
      0
    ],
    [
      7,
      12
    ],
    [
      7,
      15
    ],
    [
      8,
      4
    ],
    [
      8,
      5
    ],
    [
      8,
      13
    ],
    [
      8,
      15
    ],
    [
      9,
      10
    ],
    [
      10,
      0
    ],
    [
      13,
      3
    ],
    [
      13,
      5
    ],
    [
      13,
      9
    ],
    [
      14,
      10
    ],
    [
      14,
      13
    ],
    [
      14,
      15
    ],
    [
      15,
      10
    ],
    [
      16,
      7
    ],
    [
      16,
      9
    ]
  ],
  "terminal_states": [],
  "rewards": [
    {
      "state": [
        0,
        16
      ],
      "value": 1.0
    },
    {
      "state": [
        16,
        2
      ],
      "value": 1.0
    },
    {
      "state": [
        13,
        0
      ],
      "value": 1.0
    },
    {
      "state": [
        11,
        11
      ],
      "value": 1.0
    },
    {
      "state": [
        4,
        4
      ],
      "value": -1.0
    },
    {
      "state": [
        10,
        12
      ],
      "value": -1.0
    },
    {
      "state": [
        9,
        1
      ],
      "value": -1.0
    },
    {
      "state": [
        10,
        10
      ],
      "value": -1.0
    },
    {
      "state": [
        2,
        4
      ],
      "value": -1.0
    }
  ],
  "p_forward": 0.8,
  "gamma": 0.99,
  "step_reward": -0.05,
  "start_state": [
    16,
    0
  ]
}
